export { mainCategoryData, subCategoryData } from './data/analyticsData.js';
export { coordinators, categories, rawData } from './data/coordinatorData.js';
export { DEVELOPMENT_THEMES, FAMILY_HUB } from './data/developmentData.js';

export const COLORS = {
  'בירוקרטיה וזכויות': '#4f5e7f',
  'בריאות ורווחה': '#ca8a04',
  'לוגיסטיקה ודיגיטל': '#596067',
  'סיוע כלכלי ומגורים': '#445272',
  'פנאי ושונות': '#d97706',
};

export const BRAND_CHART_COLORS = ['#4f5e7f', '#ca8a04', '#445272', '#596067', '#d97706', '#787c75'];

export const LABELS = {
  all: 'הכל',
  allCategories: 'כל הקטגוריות',
  months: ['ינואר', 'פברואר', 'מרץ', 'אפריל'],
  monthsShort: ['ינו', 'פבר', 'מרץ', 'אפר'],
  appTitle: 'מערכת ניתוח מענים מאוחדת',
  appSubtitle: 'בחינת פריסת משימות ותפוצה לדיוק מענים · ינואר–אפריל (ניתוח) | ינואר (מתכללים)',
  analysisGoal:
    'מטרת הניתוח: לבחון את פריסת המשימות ואת התפוצה על משפחות בטיפול, כדי לדייק את סוגי המענים והפתרונות.',
  sectionAnalytics: '📊 ניתוח מענים (ינואר–אפריל)',
  sectionCoordinators: '👥 מענים לפי מתכללים (ינואר)',
  tabIntensity: '📉 פריסה, תפוצה ופילוח',
  tabSpread: '🔎 טבלת פיזור מורחבת',
  tabMatrix: '🧠 מטריצת החלטות (2D/3D)',
  tabOverview: '📊 פילוח כללי',
  tabCoordOverview: '📋 תקציר ופעילות',
  tabCoordHeatmap: '🔥 פיזור עומסים',
  tabCoordDna: '🧬 DNA מתכללים',
  tab3d: '🚀 תלת-מימד אינטראקטיבי',
  tab2d: '📊 דו-מימד (2D)',
  fullscreen: '🖥️ מסך מלא',
  closeFullscreen: '❌ סגור מסך מלא',
  legend: 'מקרא סיווגים:',
  families: 'משפחות בטיפול',
  familiesShort: 'משפ׳ בטיפול',
  tasks: 'משימות',
  days: 'ימים',
  dayShort: 'ימ׳',
  inquiries: 'פניות',
  searchPlaceholder: 'חפש משימה...',
  noResults: 'לא נמצאו משימות.',
  noDataSpread: 'לא נמצאו נתונים תואמים.',
  matrixTitle: 'מטריצת החלטות להעברת שרביט',
  matrixDescBefore: 'מיקום ברביע הצהוב מצביע על צורך ב',
  matrixDescBold: 'דיוק מענה והפניה לרפרנט',
  matrixDescAfter: ' — לפי תפוצה, מאמץ תפעולי ונפח משימות.',
  axisFamilies: 'משפחות בטיפול (ייחודיות)',
  axisSpread: 'תפוצה — משפחות בטיפול',
  axisEffort: 'מאמץ תפעולי - ימי טיפול נדרשים',
  axisTasksVolume: 'נפח משימות',
  qHandoff: 'רביע העברת שרביט',
  qNiche: 'רביע מומחיות נישה',
  qBroad: 'טיפול שוטף נרחב',
  qQuick: 'פעולות בזק',
  matrixFocusTitle: 'מצב פוקוס — רביע',
  matrixFocusTravel: 'מעבר סינמטי…',
  matrixFocusExit: 'יציאה ממצב פוקוס',
  matrixFocusHint: 'בחר רביע מהרשימה · לחץ על כדור לסטטיסטיקות · גרור לסיבוב',
  matrixFocusPoints: 'משימות ברביע',
  matrix3dStatsTitle: 'תת-סיווג נבחר',
  matrix3dStatsClose: 'סגור',
  matrix3dStatsMonthly: 'פירוט חודשי (ינואר–אפריל)',
  matrix3dQuadrant: 'רביע במטריצה',
  matrix3dWhyQuadrant: 'למה ברביע הזה?',
  matrix3dAxisSpread: 'ציר תפוצה (X)',
  matrix3dAxisEffort: 'ציר מאמץ (Y)',
  matrix3dAxisVolume: 'ציר נפח (Z)',
  matrix3dClickHint: 'לחץ על כדור לסטטיסטיקות מלאות',
  matrix3dSoundMute: 'השתק צליל טיסה',
  matrix3dSoundUnmute: 'הפעל צליל טיסה',
  overviewSectionTitle: 'פילוח כללי — מבט על תקופה',
  overviewMain: 'עומס לפי קטגוריה ראשית',
  overviewMainDesc:
    'משפחות ייחודיות עם פעילות בקטגוריה (ינואר–אפריל) · SLA ממוצע לסגירה. משימות שלא נסגרו — המדד מתייחס ליום הניתוח.',
  overviewSub:
    'תתי-סיווג מובילים (10 ראשונים)',
  overviewSubDesc:
    'משפחות ייחודיות ומשך טיפול ממוצע לכל תת-סיווג. משימות שלא נסגרו — המדד מתייחס ליום הניתוח.',
  fullscreenTitle: 'מטריצת החלטות אסטרטגית - מסך מלא',
  fullscreenDesc: 'פריסת משימות ותפוצה על משפחות בטיפול — לדיוק מענים.',
  chartMonthlyUniqueFam: 'משפחות ייחודיות',
  chartMonthlyTasks: 'משימות',
  chartFam: 'משפחות ייחודיות',
  chartTasks: 'משימות',
  trendSectionTitle: 'מגמה חודשית לתת-סיווג נבחר',
  trendSectionDesc: 'לכל חודש: כמה משפחות ייחודיות פנו במשימה מסוג זה, מול מספר המשימות.',
  intensityTitle: 'אפיון נפח משימות:',
  ratioLabel: 'יחס משימות למשפחה ייחודית',
  totalLabel: 'סך הכל (ינו׳-אפר׳)',
  spreadTitle: 'טבלת פיזור מורחבת',
  spreadUniqueFamilies: 'משפחות ייחודיות',
  spreadUniqueFamiliesShort: 'משפ׳ ייחודיות',
  spreadMonthFamiliesHint: 'כמה משפחות שונות פנו במשימה מסוג זה באותו חודש',
  spreadDesc:
    'השוואה חודשית לכל תת-סיווג: מספר משפחות ייחודיות שפתחו/קיבלו משימה כזו בחודש, מול מספר המשימות. היחס הכללי מסייע לזהות תפוצה רחבה או ריכוז פעילות.',
  intensityCol: 'יחס משימות למשפחה',
  heatmapTasksTitle: 'מפת פריסת משימות',
  heatmapTasksDesc:
    'מפת חום: נפח משימות לפי חודש. לחץ על שורה לפירוט משפחות ייחודיות מול משימות.',
  heatmapMonthHint: 'משפ׳ ייחודיות / משימות',
  decisionTitle: 'פריסת משימות ותפוצת מענים',
  decisionBody:
    'השוואה בין משפחות ייחודיות למספר משימות מאפשרת לזהות עומס רוחבי (תפוצה) או מרוכז — לדיוק המענים.',
  decisionBodyDetail:
    'שילוב בין מספר משפחות ייחודיות לבין מספר המשימות מאפשר לזהות האם קפיצה בעומס נובעת מ<strong>תפוצה רחבה</strong> על משפחות רבות, או מ<strong>ריכוז משימות</strong> אצל מעט משפחות (לדוגמה: מוניות, סיוע משפטי) — כדי לדייק את סוג המענה.',
  kpiFamilies: 'משפחות ייחודיות (שיא חודשי)',
  kpiTasks: 'סה״כ משימות',
  kpiSla: 'SLA ממוצע',
  kpiSubCategories: 'תתי-סיווג',
  badgeExtreme: 'מורכבות קיצונית',
  badgeExtremeHint: 'מעל 1.8 משימות למשפחה',
  badgeMedium: 'עומס ממוצע',
  badgeMediumHint: '~ 1.5 משימות למשפחה',
  badgeSmooth: 'שירות חלק',
  badgeSmoothHint: 'יחס 1:1 למשפחה',
  thSub: 'תת-סיווג',
  thCategory: 'קטגוריה ותת-סיווג',
  hoverX: 'תפוצה (X):',
  hoverY: 'משך טיפול (Y):',
  hoverZ: 'סך משימות (Z):',
  axisLegendTitle: 'מקרא צירים:',
  axisX: 'ציר X אופקי: תפוצה (משפחות בטיפול)',
  axisY: 'ציר Y אנכי: זמן טיפול (SLA)',
  slaDefinition:
    'משך זמן ממוצע לסגירת מעגל טיפול במענה. במשימות שלא נסגרו — המדד מתייחס ליום הניתוח.',
  slaOpenTasksNote: 'משימות שלא נסגרו — המדד מתייחס ליום הניתוח.',
  axisZ: 'ציר Z עומק: נפח משימות',
  axisHint: '* גרור עכבר לסיבוב | גלול לזום',
  loading3d: 'טוען מרחב תלת-מימד...',
  loadingDevelopment3d: 'טוען מפת מענים תלת-מימדית...',
  developmentPageTitle: 'פיתוח ומיצוי מענים במנהלת',
  developmentEyebrow: 'מעטפת אזרחית · ליווי ושיקום',
  developmentPageIntro:
    'מעבר מניהול משבר לרצף שיקומי ארוך טווח — המשפחה במרכז, והמענים מקיפים אותה כמעגל הגנה מתואם.',
  developmentOrbitCaption: 'בחרו מענה במעגל — או גללו בין הנושאים',
  developmentTimelineLabel: 'כל נושאי המעטפת',
  developmentRingHint: 'לחצו על נקודה במעגל · חצים · פס התחתון',
  developmentNavUp: 'מענה קודם',
  developmentNavDown: 'מענה הבא',
  developmentContentLabel: 'תוכן מענה',
  tasksName: 'משימות',
  tooltipFamilies: 'משפחות ייחודיות',
  tooltipIntensityRatio: 'יחס משימות למשפחה',
  tooltipAvgSla: 'זמן טיפול ממוצע',
  tooltipSpread: 'תפוצה',
  tooltipSla: 'מאמץ (SLA)',
};
