export { mainCategoryData, subCategoryData } from './data/analyticsData.js';
export { coordinators, categories, rawData } from './data/coordinatorData.js';

export const COLORS = {
  'בירוקרטיה וזכויות': '#3B82F6',
  'בריאות ורווחה': '#EF4444',
  'לוגיסטיקה ודיגיטל': '#8B5CF6',
  'סיוע כלכלי ומגורים': '#10B981',
  'פנאי ושונות': '#F59E0B',
};

export const BRAND_CHART_COLORS = ['#004795', '#FFC107', '#002855', '#FF8F00', '#16a34a', '#4b5563'];

export const LABELS = {
  all: 'הכל',
  allCategories: 'כל הקטגוריות',
  months: ['ינואר', 'פברואר', 'מרץ', 'אפריל'],
  monthsShort: ['ינו', 'פבר', 'מרץ', 'אפר'],
  appTitle: 'מערכת ניתוח מענים מאוחדת',
  appSubtitle: 'ניתוח ארגוני (ינואר–אפריל) ופילוח לפי מתכללים (ינואר)',
  sectionAnalytics: '📊 ניתוח מענים (ינואר–אפריל)',
  sectionCoordinators: '👥 מענים לפי מתכללים (ינואר)',
  tabIntensity: '📉 תפוצה לעומת עצימות',
  tabSpread: '🔎 טבלת פיזור מורחבת',
  tabMatrix: '🧠 מטריצת החלטות (2D/3D)',
  tabOverview: '📊 פילוח כללי',
  tabCoordOverview: '📋 תקציר ופעילות',
  tabCoordHeatmap: '🔥 פיזור עומסים',
  tabCoordDna: '🧬 DNA מתכללים',
  tab3d: '🚀 תלת-מימד אינטראקטיבי',
  tab2d: '📊 דו-מימד (2D)',
  fullscreen: '🖥️ מסך מלא',
  closeFullscreen: '❌ סגור מסך מלא',
  legend: 'מקרא סיווגים:',
  families: 'משפחות',
  familiesShort: 'משפ׳',
  tasks: 'משימות',
  days: 'ימים',
  dayShort: 'ימ׳',
  inquiries: 'פניות',
  searchPlaceholder: 'חפש משימה...',
  noResults: 'לא נמצאו משימות.',
  noDataSpread: 'לא נמצאו נתונים תואמים.',
  matrixTitle: 'מטריצת החלטות להעברת שרביט',
  matrixDescBefore: 'זיהוי ויזואלי של תהליכים דורשי התערבות: ',
  matrixDescBold: 'משימות ברביע האדום',
  matrixDescAfter: ' מחייבות מינוי רפרנט מקצועי.',
  axisFamilies: 'משפחות ייחודיות',
  axisSpread: 'תפוצה - כמות משפחות בטיפול',
  axisEffort: 'מאמץ תפעולי - ימי טיפול נדרשים',
  axisTasksVolume: 'נפח משימות',
  qHandoff: 'רביע העברת שרביט',
  qNiche: 'רביע מומחיות נישה',
  qBroad: 'טיפול שוטף נרחב',
  qQuick: 'פעולות בזק',
  overviewMain: 'מבט על: עומס לפי סיווג ראשי',
  overviewMainDesc: 'מספר המשפחות והזמן הממוצע לסגירת מעגל.',
  overviewSub: 'רזולוציה: משימות לפי תת-סיווג',
  overviewSubDesc: 'דירוג המשימות מהנפוצה ביותר לנדירה (10 הראשונות).',
  fullscreenTitle: 'מטריצת החלטות אסטרטגית - מסך מלא',
  fullscreenDesc: 'איפיון וסיווג משימות תחת מטה בקרה ארצי.',
  chartFam: 'תפוצה: משפחות מעורבות',
  chartTasks: 'עומס: סך משימות שנפתחו',
  intensityTitle: 'אפיון עצימות:',
  ratioLabel: 'יחס משימות למשפחה',
  totalLabel: 'סך הכל (ינו׳-אפר׳)',
  spreadTitle: 'טבלת פיזור מורחבת',
  spreadDesc: 'השוואה חודשית מפורטת: כמות המשפחות אל מול המשימות בכל תת-סיווג.',
  intensityCol: 'יחס עצימות כללי',
  heatmapTasksTitle: 'מפת עומסים לפי משימות',
  heatmapTasksDesc: 'מפת החום משקפת את סך המשימות. לחץ על שורה לניתוח השוואתי.',
  decisionTitle: 'החלטה מבוססת נרטיב: תפוצה מול עצימות',
  decisionBody: 'השוואה בין מספר משפחות למספר משימות מאפשרת לזהות אם עומס רוחבי או נקודי.',
  badgeExtreme: 'מורכבות קיצונית',
  badgeExtremeHint: 'מעל 1.8 משימות למשפחה',
  badgeMedium: 'עומס ממוצע',
  badgeMediumHint: '~ 1.5 משימות למשפחה',
  badgeSmooth: 'שירות חלק',
  badgeSmoothHint: 'יחס 1:1 למשפחה',
  thSub: 'תת-סיווג',
  thCategory: 'קטגוריה ותת-סיווג',
  hoverX: 'תפוצה (X):',
  hoverY: 'משך טיפול (Y):',
  hoverZ: 'סך משימות (Z):',
  axisLegendTitle: 'מקרא צירים:',
  axisX: 'ציר X אופקי: תפוצה (משפחות)',
  axisY: 'ציר Y אנכי: זמן טיפול (SLA)',
  axisZ: 'ציר Z עומק: נפח משימות',
  axisHint: '* גרור עכבר לסיבוב | גלול לזום',
  loading3d: 'טוען מרחב תלת-מימד...',
  tasksName: 'משימות',
  tooltipFamilies: 'משפחות מלווות',
  tooltipAvgSla: 'זמן טיפול ממוצע',
  tooltipSpread: 'תפוצה',
  tooltipSla: 'מאמץ (SLA)',
};
